[package]
name = "skbloom"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "skbloom"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.0"
fasthash = '0.4.0'
